spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true

  datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/webfounder
          username: root
          password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/webfounder
#    username: root
#    password: 1234

logging:
  level:
    org.hibernate.SQL: debug

<<<<<<< Updated upstream
=======
secret:
  jwt: aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789AbCdEfGhIjKlMnOpQrStUvWxYz
>>>>>>> Stashed changes
